export enum Events {
  READ_URL_EVENT = "READ_URL_EVENT",
  READ_URL_SUCCESS_EVENT = "READ_URL_SUCCESS_EVENT",
  DOWNLOAD_VIDEO_EVENT = "DOWNLOAD_VIDEO_EVENT",
  DOWNLOAD_VIDEO_STARTED_EVENT = "DOWNLOAD_VIDEO_STARTED_EVENT",
  DOWNLOAD_VIDEO_SUCCESS_EVENT = "DOWNLOAD_VIDEO_SUCCESS_EVENT",
  DOWNLOAD_VIDEO_FAIL_EVENT = "DOWNLOAD_VIDEO_FAIL_EVENT",
  DOWNLOAD_VIDEO_PROGRESS_EVENT = "DOWNLOAD_VIDEO_PROGRESS_EVENT",
}
